name: docs_ZXQEP
channels:

  - conda-forge

  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-copybutton
  - sphinx-autoapi
  - jupyter-sphinx
  - ipykernel



    # Pip-only installs
  - pip:
    - -e ../
    - pyzx

